#!/usr/bin/env python

from __future__ import unicode_literals, print_function
import subprocess, sys, os, re
OK = 0
WARNING = 1
CRITICAL = 2
UNKNOWN = 3
def package_installed(package_name):
    """ @since: 2014-08-04
        @author: Jivan
        @return: True if \a package_name is installed, False if not.
    """
    co = subprocess.check_output('dpkg -l {pn} | grep {pn}'.format(pn=package_name), shell=True)
    m = re.search(package_name, co)
    ret = True if m else False
    return ret
def config_file_contains(config_filename, content_regex):
    """ @since: 2014-08-04
        @author: Jivan
        @return: True if \a content_regex matches content in \a config_filename.
    """
    cf = open(config_filename, 'r')
    fc = cf.read()
    sm = re.search(content_regex, fc, flags=re.MULTILINE)
    ret = bool(sm)
    return ret
def get_config_value(config_filename, config_value_regex):
    """
        @since: 2014-08-06
        @author: Jivan
        @return: The value of the config variable described by \a config_value_regex.
        @param config_value_regex: a regular expression which will match the config variable
            and it's value as the first group.
            Example: if a config variable looks like 'mysetting: <n>' config_value_regex would
                be 'mysetting: (\d+)'
    """
    cf = open(config_filename, 'r')
    fc = cf.read()
    sm = re.search(config_value_regex, fc, flags=re.MULTILINE)
    if not sm or len(sm.groups()) != 1:
        ret = None
    else:
        ret = sm.group(1)
    return ret
try:
    if not package_installed('unattended-upgrades'):
        print("CRITICAL - Package 'unattended-upgrades' not installed")
        sys.exit(CRITICAL)
    expected_content_regex = r'^\s*' + re.escape(r'"${distro_id}:${distro_codename}-security";')
    config_filename = '/etc/apt/apt.conf.d/50unattended-upgrades'
    if not config_file_contains(config_filename, expected_content_regex):
        print("CRITICAL - 'unattended-upgrades' is not configured to install security updates")
        sys.exit(CRITICAL)
    config_filename = '/etc/apt/apt.conf.d/20auto-upgrades'
    if not os.path.isfile(config_filename):
        config_filename = '/etc/apt/apt.conf.d/10periodic'
    if not os.path.isfile(config_filename):
        config_filename = '/etc/apt/apt.conf.d/50unattended-upgrades'
    config_variable_regexes = [
        re.escape(r'APT::Periodic::Unattended-Upgrade "') + r'(\d+)' + re.escape(r'";'),
        r'APT::Periodic::Update-Package-Lists "(\d+)";',
    ]
    for cvr in config_variable_regexes:
        val = get_config_value(config_filename, cvr)
        val = None if val is None else int(val)
        if not val:
            print("CRITICAL - In {}: {} is set to {}".format(config_filename, cvr, val))
            sys.exit(CRITICAL)
        if cvr == config_variable_regexes[0]:
            unattended_upgrade_period = val
    reboot_required = os.path.exists('/var/run/reboot-required')
    if reboot_required:
        print("WARNING - Server requires a reboot")
        sys.exit(WARNING)
    else:
        print("OK - unattended_upgrades runs every {} days".format(unattended_upgrade_period))
        sys.exit(OK)
except Exception as ex:
    print(ex)
    pass
print("UNKNOWN - Check failed with unknown error")
sys.exit(UNKNOWN)
